# # # docker-compose.yml
# # version: '3'
# # services:
# #   web:
# #     build: .
# #     command: python manage.py runserver 0.0.0.0:8000
# #     volumes:
# #       - .:/app
# #     ports:
# #       - "8000:8000"
# #     depends_on:
# #       - redis
# #   celery:
# #     build: .
# #     command: celery -A sentiment_nwt_project worker --loglevel=info
# #     volumes:
# #       - .:/app
# #     depends_on:
# #       - redis
# #   redis:
# #     image: "redis:alpine"
# #     ports:
# #       - "6379:6379"

# # docker-compose.yml
# version: '3'
# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#   celery:
#     build: .
#     command: celery -A sentiment_nwt_project worker --loglevel=info
#     volumes:
#       - .:/app
#     depends_on:
#       - redis
#   redis:
#     image: "redis:7.4.0"
#     command: redis-server --appendonly yes
#     ports:
#       - "6380:6379"

version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=sentiment_nwt_project.settings
 
  celery:
    build: .
    command: celery -A sentiment_nwt_project worker --loglevel=info
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=sentiment_nwt_project.settings
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"






