# Generated by Django 5.1 on 2024-08-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailanalysis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
