# Generated by Django 5.1 on 2024-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0003_emailanalysis_email_alter_emailanalysis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailanalysis',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
