# Generated by Django 4.1.6 on 2024-08-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0005_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='sentiment_huggingface',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='sentiment_openai',
            new_name='sentiment',
        ),
        migrations.RemoveField(
            model_name='emailanalysis',
            name='probability_huggingface',
        ),
        migrations.RemoveField(
            model_name='emailanalysis',
            name='probability_openai',
        ),
        migrations.RemoveField(
            model_name='emailanalysis',
            name='time_consumed_huggingface',
        ),
        migrations.RemoveField(
            model_name='emailanalysis',
            name='time_consumed_openai',
        ),
    ]
