# Generated by Django 4.1.6 on 2024-08-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0006_rename_sentiment_huggingface_emailanalysis_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailanalysis',
            name='category',
        ),
    ]
