# Generated by Django 5.1 on 2024-08-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0007_remove_emailanalysis_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailanalysis',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESA.email'),
        ),
    ]
