# Generated by Django 5.1 on 2024-08-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0008_alter_emailanalysis_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailanalysis',
            name='content',
        ),
    ]
