# Generated by Django 5.1 on 2024-08-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0009_remove_emailanalysis_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailanalysis',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
