# Generated by Django 5.1 on 2024-08-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0010_emailanalysis_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='emailanalysis',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ESA.email'),
        ),
    ]
