# Generated by Django 5.1 on 2024-08-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0011_delete_test_alter_emailanalysis_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
