# Generated by Django 5.1 on 2024-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0012_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailanalysis',
            name='content',
            field=models.TextField(),
        ),
    ]
