# Generated by Django 5.1 on 2024-08-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0013_alter_emailanalysis_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailanalysis',
            name='email',
        ),
    ]
