# Generated by Django 5.1 on 2024-08-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0014_remove_emailanalysis_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='content',
            new_name='content_gbr',
        ),
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='sentiment',
            new_name='sentiment_gbr',
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='content_hf',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='sentiment_hf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
