# Generated by Django 5.1 on 2024-08-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0015_rename_content_emailanalysis_content_gbr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='content_gbr',
            new_name='content_berttweet',
        ),
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='content_hf',
            new_name='content_huggingface',
        ),
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='sentiment_gbr',
            new_name='sentiment_berttweet',
        ),
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='sentiment_hf',
            new_name='sentiment_huggingface',
        ),
    ]
