# Generated by Django 5.1 on 2024-08-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESA', '0017_alter_emailanalysis_content_huggingface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailanalysis',
            old_name='content_berttweet',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='emailanalysis',
            name='content_huggingface',
        ),
    ]
